# pip install pygments mkdocs-material pymdown-extensions
site_name: camlhmp
site_author: Robert A. Petit III
site_description: 🐪 Classification through yAML Heuristic Mapping Protocol 🐪
copyright: >
  Copyright © 2024-2024 Robert A. Petit III. All rights reserved. <a href="#__consent">Change Cookie Settings</a>

site_url: https://rpetit3.github.io/camlhmp/
repo_url: https://github.com/rpetit3/camlhmp
dev_addr: 0.0.0.0:8000

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top

plugins:
  - privacy
  - search:
      lang: en
  - social:
      enabled: true
      cache: true
      cards: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [camlhmp]
          options:
            show_source: true
            show_symbol_type_heading: false

extra:
  analytics:
    provider: google
    property: G-CE4JZPXDE8
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rpetit3
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rpetit3
  version:
    provider: mike
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - custom/magnific-popup.css
  - custom/extra.css

extra_javascript:
  - custom/fontawesome.js
  - custom/jquery.min.js
  - custom/jquery.magnific-popup.min.js
  - custom/extra.js

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 'camlhmp':
    - 'Introduction': 'index.md'
    - 'Installation': 'installation.md'
  - 'API Reference':
    - 'Overview': 'api/index.md'
    - 'Engines': 
      - "Blast": 'api/engines/blast.md'
    - 'Parsers': 
      - "Blast": 'api/parsers/blast.md'

